version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: daily
      time: "12:00"
    commit-message:
      prefix: 👷
    labels: [github-actions, dependencies]
  - package-ecosystem: cargo
    directory: /
    schedule:
      timzone: America/Los_Angeles
      interval: daily
      time: "12:00"
    commit-message:
      prefix: ⬆
    labels: [rust, dependencies]
