#!/bin/bash

source "$(dirname "${BASH_SOURCE[0]}")/github"

function sccache::acquire {
  compgen "${1}" > /dev/null && return
  declare pattern=$(basename "${1}")
  declare dir=$(dirname "${1}")
  echo "Acquiring mozilla/sccache asset matching '${pattern}' into " $(github::path "${dir}")
  gh release download \
    --repo mozilla/sccache \
    --pattern "${pattern}" \
    --dir "${dir}"
}

function sccache::extract {
  declare tarball=$(ls -1 "${1}" | head -1)
  declare tar=$(test "${RUNNER_OS}" != "macOS" && echo "tar" || echo "gtar")
  echo "Extracting sccache from $(github::path ${tarball})"
  ${tar} --file=${tarball} --strip-components=1 \
    --extract --gunzip --wildcards --verbose \
    "*/sccache*"
}

function sccache::install {
  echo "Installing sccache to $(github::path ${1})"
  install -d "${1}"
  install -v sccache "${1}"
  echo "SCCACHE_DIR=$(github::path "${HOME}/.cache/sccache")" >> ${GITHUB_ENV}
  echo "SCCACHE_CACHE_SIZE=5G" >> ${GITHUB_ENV}
  github::path "${1}" >> ${GITHUB_PATH}
  test -x "${1}/sccache" || github::error "$(github::path ${1}/sccache) is not executable"
}

github::environment RUNNER_OS

declare tarball="${HOME}/.cache/downloads/sccache-v*x86_64*$(github::platform "${RUNNER_OS}")*.tar.gz"
github::group "Acquire sccache binary" sccache::acquire "${tarball}"
github::group "Extract sccache binary" sccache::extract "${tarball}"
github::group "Install sccache binary" sccache::install "${HOME}/.local/bin"
