#!/bin/bash

source "$(dirname "${BASH_SOURCE[0]}")/github"

function cargo-hack::acquire {
  compgen "${1}" > /dev/null && return
  declare pattern=$(basename "${1}")
  declare dir=$(dirname "${1}")
  echo "Acquiring taiki-e/cargo-hack asset matching '${pattern}' into" $(github::path "${dir}")
  gh release download \
    --repo taiki-e/cargo-hack \
    --pattern "${pattern}" \
    --dir "${dir}"
}

function cargo-hack::extract {
  declare tarball=$(ls -1 "${1}" | head -1)
  declare tar=$(test "${RUNNER_OS}" != "macOS" && echo "tar" || echo "gtar")
  echo "Extracting sccache from $(github::path ${tarball})"
  ${tar} --file=${tarball} --extract --gunzip --verbose
}

function cargo-hack::install {
  echo "Install cargo-hack to $(github::path ${1})"
  install -d "${1}"
  install -v cargo-hack "${1}"
  github::path "${1}" >> ${GITHUB_PATH}
  test -x "${1}/cargo-hack" || github::error "$(github::path ${1}/cargo-hack) is not executable"
}

github::environment RUNNER_OS

declare tarball="${HOME}/.cache/downloads/cargo-hack*$(github::platform "${RUNNER_OS}")*.tar.gz"
github::group "Acquire cargo-hack binary" cargo-hack::acquire "${tarball}"
github::group "Extract cargo-hack binary" cargo-hack::extract "${tarball}"
github::group "Install cargo-hack binary" cargo-hack::install "${HOME}/.local/bin"
