name: Lint Actions
on:
  pull_request:
    paths: [.github/**.yml]
    types: [synchronize, edited, opened]
  push:
    paths: [.github/**.yml]
jobs:
  skip:
    name: Check Duplicate Actions
    #continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should_skip }}
    steps:
      - name: Skip Duplicate Actions (Lint Actions)
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5
        id: skip-check
  actions:
    name: Action Workflows
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@c6ee1eb0a5d47b2af53a203652b5dac0b6c4016e # v1
  yaml:
    name: YAML
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Review Dog - yamllint
        uses: reviewdog/action-yamllint@e419e43894e391d358ebf996800673d72de6c69b # v1
        with:
          yamllint_flags: >-
            --config-file ${{github.workspace}}/.github/settings/yamllint.yml
            ${{github.workspace}}
