name: Lint Actions
on:
  pull_request:
    paths: [.github/**.yml]
    types: [synchronize, edited, opened]
  push:
    paths: [.github/**.yml]
jobs:
  skip:
    name: Check Duplicate Actions
    #continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should_skip }}
    steps:
      - name: Skip Duplicate Actions (Lint Actions)
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5
        id: skip-check
  actions:
    name: Action Workflows
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@9d8b58041eed1373f173e91b9a3db5a844197236 # v1
  yaml:
    name: YAML
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Review Dog - yamllint
        uses: reviewdog/action-yamllint@04e023c110e088170fb3dea6ab7bea64f04d0db0 # v1
        with:
          yamllint_flags: >-
            --config-file ${{github.workspace}}/.github/settings/yamllint.yml
            ${{github.workspace}}
