name: Audit
on:
  pull_request:
    paths: [Cargo.toml, Cargo.lock]
  push:
    paths: [Cargo.toml, Cargo.lock]
jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        uses: actions-rs/audit-check@v1
        with:
          token: ${{github.token}}
