name: Audit
on:
  pull_request:
    paths: [Cargo.toml, Cargo.lock]
    types: [synchronize, opened, edited]
  push:
    paths: [Cargo.toml, Cargo.lock]
jobs:
  skip:
    name: Check Duplicate Actions
    # continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should_skip }}
    steps:
      - name: Skip Duplicate Actions (Audit)
        uses: fkirc/skip-duplicate-actions@v3
        id: skip-check
  audit:
    name: Audit
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.output.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit Check
        uses: actions-rs/audit-check@v1
        with:
          token: ${{github.token}}
