name: Code Coverage
on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches: main
jobs:
  coverage:
    name: Code Coverage
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Authenticate GitHub CLI
        run: echo ${{github.token}} | gh auth login --with-token
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@master # renovate: tag=v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
      - name: Setup Shared Compilation Cache
        uses: baptiste0928/cargo-install@2cfb0024938d23011106cbf127b393bc83fddba1 # v1
        with:
          crate: sccache
      - name: Setup Cargo hack
        uses: bruxisma/setup-cargo-hack@1d7117a0b3be8457283a783e4065b7ba649c5d54 # renovate: tag=v1
      - name: Setup grcov
        uses: baptiste0928/cargo-install@2cfb0024938d23011106cbf127b393bc83fddba1 # v1
        with:
          crate: grcov
      - name: Setup Shared Cache Directory
        shell: bash
        run: |
          declare path="${HOME}/.cache/sccache"
          if test "${RUNNER_OS}" = "Windows"; then
            path=$(cygpath --windows "${path}")
          fi
          echo "SCCACHE_DIR=${path}" >> "${GITHUB_ENV}"
      - name: Restore Cargo Cache
        uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3
        with:
          restore-keys: ${{runner.os}}-cargo-
          key: ${{runner.os}}-cargo-${{hashFiles('**/Cargo.lock')}}
          path: |
            ${{github.workspace}}/target
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
      - name: Restore sccache build artifacts
        uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3
        with:
          restore-keys: ${{runner.os}}-nightly-coverage-
          key: ${{runner.os}}-nightly-coverage-${{hashFiles('**/Cargo.lock')}}
          path: ${{env.SCCACHE_DIR}}
      - name: Run Tests (coverage)
        run: |
          echo "${env:PATH}"
          cargo install --list
          cargo hack test --profile=coverage --locked --each-feature
        env:
          LLVM_PROFILE_FILE: target/coverage/outcome-%p-%m.profraw
          RUSTC_WRAPPER: sccache
          RUSTDOCFLAGS: >-
            -C instrument-coverage
            -Zunstable-options
            --persist-doctests ${{github.workspace}}/target/coverage
          RUSTFLAGS: -C instrument-coverage
      - name: Collect Coverage
        run: >-
          grcov ${{github.workspace}}
          --binary-path ${{github.workspace}}/target/coverage
          --output-path ${{github.workspace}}/coverage.info
          --output-type lcov
          --source-dir ${{github.workspace}}
          --ignore "/*"
          --ignore "C:/*"
          --ignore "../*"
          --ignore-not-existing
          --branch
      - name: Check coverage.info exists
        run: test -f ${{github.workspace}}/coverage.info
      - name: Upload Code Coverage
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3
        with:
          fail_ci_if_error: true
          directory: ${{github.workspace}}
          files: coverage.info
      - name: Upload Code Coverage Artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: ${{matrix.os}}-coverage.info
          path: coverage.info
          if-no-files-found: error
