name: Release
on:
  push:
    tags: ['v*']
jobs:
  validate:
    name: Validate Release
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{matrix.os}}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@0e66bd3e6b38ec0ad5312288c83e47c143e6b09e # v1
        with:
          toolchain: stable
          profile: minimal
      - name: Setup Cargo Hack
        uses: bruxisma/setup-cargo-hack@1d7117a0b3be8457283a783e4065b7ba649c5d54 # tag=v1
      - name: Validate Publish
        run: cargo hack publish --dry-run --each-feature --locked
  publish:
    needs: [validate]
    name: Publish Crate
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Set Git Branch
        run: git switch -c ${{github.ref_name}}
      - name: Install Cargo Release
        uses: baptiste0928/cargo-install@30f432979e99f3ea66a8fa2eede53c07063995d8 # v2
        with:
          crate: cargo-release
      - name: Get Crate Version
        shell: bash
        id: metadata
        run: |
          declare query='.packages[] | select(.name | contains("outcome")).version'
          echo "::set-output name=version::$(cargo metadata --format-version=1 | jq -r "${query}")"
      - name: Verify Version
        run: test "v${{steps.metadata.outputs.version}}" = "${{github.ref_name}}"
      - name: Configure Git User
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: Publish Crate
        run: >-
          cargo release
          --token ${{secrets.CARGO_REGISTRY_TOKEN}}
          --tag-name ${{github.ref_name}}
          --no-confirm
          --no-verify
          --no-push
          --no-tag
          --execute
      - name: Yank On Failure
        shell: bash
        if: failure()
        run: >-
          cargo yank
          --vers ${{steps.metadata.outputs.version}}
          --token ${{secrets.CARGO_REGISTRY_TOKEN}}
