name: Spellcheck
on:
  pull_request:
    types: [synchronize, edited, opened]
jobs:
  skip:
    name: Check Duplicate Actions
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{steps.skip-check.outputs.should_skip}}
    steps:
      - name: Skip Duplicate Actions (Spellcheck)
        uses: fkirc/skip-duplicate-actions@9d116fa7e55f295019cfab7e3ab72b478bcf7fdd # tag=v4
        id: skip-check
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Checking Spelling
        uses: crate-ci/typos@69fe45d5e7b7d34d5574485b1714c76d4acc1651 # tag=v1.11.0
        with:
          config: ${{github.workspace}}/.github/settings/typos.yml
