name: Spellcheck
on:
  pull_request:
    types: [synchronize, edited, opened]
jobs:
  skip:
    name: Check Duplicate Actions
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{steps.skip-check.outputs.should_skip}}
    steps:
      - name: Skip Duplicate Actions (Spellcheck)
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5
        id: skip-check
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Checking Spelling
        uses: crate-ci/typos@e12da5495cfdcc860f4a8e2b5b23eb171d5e5f70 # v1.22.2
        with:
          config: ${{github.workspace}}/.github/settings/typos.yml
